@startuml timeline
!theme toy
Project starts the 1th of June 2022
[Review report] starts 2022-06-01 and lasts 5 days
[Linking MongoDB and ElasticSearch] starts 2022-06-06 and lasts 2 week
[Display of ElasticSearch results] starts 2022-06-13 and lasts 12 days
[Testing of ElasticSearch results] starts 2022-06-13 and lasts 12 days
[Display in grid view] starts 2022-06-25 and lasts 8 days
[Interative card profile to profile page] starts 2022-06-27 and lasts 14 days
[Testing interative card profile] starts 2022-7-1 and lasts 12 days
[Implement 1st iteration of feed front-end] starts 2022-06-06 and lasts 18 day
[Implement 1st iteration of profile front-end] starts 2022-06-06 and lasts 18 day
[Testing] starts 2022-06-27 and lasts 3 weeks
[Project Meeting II] starts 2022-07-06 and lasts 1 day
[Project Meeting III] starts 2022-07-13 and lasts 1 day
[Refine and integration] starts 2022-07-14 and lasts 3 weeks
[Project Meeting IV] starts 2022-08-03 and lasts 1 day
[Presentation prep] starts 2022-08-03 and lasts 7 days
[Project Presentation] starts 2022-08-10 and lasts 1 day
@enduml