@startuml sage_use_cases
!theme toy
left to right direction
actor :User: as publicUser
actor :Sage user: as sage
actor :Mallory: as mallory #red

"Sign up" as (signup)
"Log in" as (login)
"Log in as Sage" as (loginAsSage)
"Log out" as (logout)
"Send request" as (sendReq)
"Cancel request" as (cancelReq)
"Accept request" as (acceptReq)
"Deny request" as (denyReq)
"Edit profile details" as (editProfile)
"Upload profile picture" as (uploadProfilePicture)
"View profile" as (viewProfile)
"Search for Sages\n(with fuzzy search)" as (search)
"View feed" as (viewFeed)
"Create new post" as (createPost)
"Comment on post" as (comment)
"Upvote post" as (upvotePost)
"Share post" as (sharePost)
"Report post" as (reportPost)
"Filter post" as (filterPost)
"View all requests" as (viewReqs)

(signup) --> (login)
(login) --> (logout)
(loginAsSage) --> (logout)


publicUser --> (signup)
publicUser --> (login)
publicUser --> (viewFeed)

sage --> (signup)
sage --> (loginAsSage)
sage --> (viewFeed)

(login) --> (editProfile)
(login) --> (search)
(login) --> (viewFeed)
(login) --> (viewReqs)

(loginAsSage) --> (editProfile)
(loginAsSage) --> (search)
(loginAsSage) --> (viewFeed)
(loginAsSage) --> (viewReqs)
(viewReqs) --> (acceptReq)      : "if user is Sage"
(viewReqs) --> (denyReq)      : "if user is Sage"
(editProfile) --> (uploadProfilePicture)


(search) --> (viewProfile)
(viewFeed) --> (viewProfile) : "if logged in"
(viewFeed) --> (createPost) : "if logged in"
(viewFeed) --> (comment) : "if logged in"
(viewFeed) --> (upvotePost) : "if logged in"
(viewFeed) --> (sharePost) : "if logged in"
(viewFeed) --> (reportPost) : "if logged in"
(viewFeed) --> (filterPost) : "if logged in"
(viewFeed) --> (sendReq) : "if logged in"
(viewProfile) --> (sendReq)
(search) --> (sendReq)
(viewReqs) --> (cancelReq) : "if user is Sage"


"Post spam or\nmalicious content" as (postSpam) #red
(postSpam) --> (createPost) #red
mallory --> (postSpam) #red

"Send request\nwith no content" as (sendReq0) #red
(sendReq0) --> (sendReq) #red
mallory --> (sendReq0) #red

"Create account\nwithout\nprofile pic" as (createAcctnopic) #red
(createAcctnopic) --> (signup) #red
mallory --> (createAcctnopic) #red

"Typing incomplete\nor fuzzy query" as (typingIncomplete) #red
(typingIncomplete) --> (search) #red
mallory --> (typingIncomplete) #red

(reportPost) -[#blue]-> (postSpam) 
(sendReq) -[#blue]-> (sendReq0) : Not allowed if content does not exceed length
(signup) -[#blue]-> (createAcctnopic) : Prompt user to upload pic, if not cannot sign up 
(search) -[#blue]-> (typingIncomplete) : Fuzzy search resolves this 


@enduml