@startuml Q6
!theme toy
class "Calculator Display" as disp {
    + result: Complex Number

    + displayResult(): String
}

class "Equation" as eq {
    + firstOperand: Operand
    + secondOperand: Operand
    + operator: Operator
}

class "Calculator" as calc {
    + equation: Equation

    + computeEquation(): Complex Number
}

class "Complex Operand" as comp {
    + realComponent: Double
    + imaginaryComponent: Double
}

interface "Operator" as operator {
    + compute(): void
}

class "Addition Operator" as add {
    + compute(): Complex Number
}

class "Subtraction Operator" as sub {
    + compute(): Complex Number
}

class "Multiplication Operator" as mul {
    + compute(): Complex Number
}

class "Division Operator" as div {
    + compute(): Complex Number
}

' switch "1..*" -- "0..*" sub 
disp --> calc
add ..|> operator
sub ..|> operator
mul ..|> operator
div ..|> operator
eq --> "0..2"comp
calc --> "0..1"eq
eq --> "0..1"operator
@enduml